// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        // throw UnsupportedError(
        //   'DefaultFirebaseOptions have not been configured for ios - '
        //   'you can reconfigure this by running the FlutterFire CLI again.',
        // );
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqAOJe3i4JFFcVuAeRoUTh3-sxw5EaVcM',
    appId: '1:1043472852661:android:3e2af1865b6f1e35cf80fc',
    messagingSenderId: '1043472852661',
    projectId: 'capstoneetravel-d42ad',
    storageBucket: 'capstoneetravel-d42ad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO4ms_bfONCohOj4Va7EyollTJKWWRxNA',
    appId: '1:1043472852661:ios:9ba2d3e11175e7c1cf80fc',
    messagingSenderId: '1043472852661',
    projectId: 'capstoneetravel-d42ad',
    storageBucket: 'capstoneetravel-d42ad.appspot.com',
    iosClientId:
        '1043472852661-8et7brqg2bcon7q7fb0jscqv7i82ouh4.apps.googleusercontent.com',
    iosBundleId: 'com.etravel.mobilePortal',
  );
}
